# Generated by Django 4.0.6 on 2022-07-07 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=100, null=True)),
                ('book_title', models.CharField(blank=True, max_length=200, null=True)),
                ('book_author', models.CharField(blank=True, max_length=100, null=True)),
                ('publish_date', models.DateField(default=datetime.date(2022, 7, 7))),
            ],
        ),
    ]
